=== xxyou00/natural-language/intents.dtd
<!ELEMENT intents (intent)*>
<!ELEMENT intent (utterance|matcher)*>
<!ATTLIST intent
        action CDATA #REQUIRED>
<!ELEMENT utterance (#PCDATA)>
<!ELEMENT matcher (#PCDATA)>

=== xxyou00/natural-language/src/test/resources/organic.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE intents PUBLIC "-//yannickl88//DTD Intents//EN"
  "https://yannickl88.github.io/natural-language/intents.dtd">

<intents>

    <!-- Greetings -->
    <intent action="Generic.Greeting">
        <utterance>hello</utterance>
        <utterance>hey</utterance>
        <utterance>hi</utterance>
    </intent>

    <!-- Help -->
    <intent action="Generic.Help">
        <utterance>help</utterance>
    </intent>

    <!-- Food orderings -->
    <intent action="Food.Create.Order">
        <utterance>order for me</utterance>
        <utterance>can I order</utterance>
    </intent>

    <!-- Food queries -->
    <intent action="Food.Query.Order">
        <utterance>what did I order</utterance>
    </intent>

</intents>

=== xxyou00/natural-language/src/test/resources/intent_matcher_loader_test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE intents PUBLIC "-//yannickl88//DTD Intents//EN"
        "https://yannickl88.github.io/natural-language/intents.dtd">

<intents>

    <!-- Just Utterances -->
    <intent action="Foo.Bar">
        <utterance>Foo Bar</utterance>
    </intent>
    <intent action="Foo.Bar">
        <utterance>Baz</utterance>
    </intent>

    <!-- Just Entities -->
    <intent action="Foo.Number">
        <matcher>nl.yannickl88.language.matcher.buildins.Number</matcher>
    </intent>

    <!-- Entity and Utterance -->
    <intent action="Foo.All">
        <utterance>foobar</utterance>
        <matcher>nl.yannickl88.language.matcher.buildins.Number</matcher>
    </intent>

</intents>
